export { About } from './About/About'
export { Contact } from './Contact/Contact'
export { Hero } from './Hero/Hero'
export { Intro } from './Intro/Intro'
export { Projects } from './Projects/Projects'
